name: pioneer_metbk
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Remove and add below packages as needed
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - netCDF4
  - pip
  - ipykernel
  - halo
  - requests
  - distributed
  - tqdm
  - bs4
  - munch
  - h5pyd
  - h5netcdf
  - urllib3
  - chardet
  - conda-build
  - wheel
  - python-dateutil
  - pytz
  - openssl
  - yaml
  - pyopenssl
  - pyyaml
  - ioos_qc
  - cmocean